### ISSUE TITLE
Apex Classes Not Loading

### ISSUE THREAD

**Issue by jawills** [Avinava/sfdc-neo#61]
When going to the Apex generator, the list of Apex classes is empty. Using a developer org.

## Steps to reproduce

1. Log in using Developer Account
2. Go to `Apex Generator`

<img width="571" alt="Screenshot 2024-01-13 at 12 54 05 PM" src="https://github.com/Avinava/sfdc-neo/assets/17165950/26fbc656-4dfc-45b2-b1d7-d738a97599d8">

**Comment by Avinava** [comment]
@jawills can you check in your web browsers console if there are any errors ?
Also if you use the refresh button next it does it load anything ?

**Comment by jawills** [comment]
@Avinava I don't see any errors in the console. Getting a 304 error on the endpoint when loading / pressing the refresh button
![Uploading Screenshot 2024-01-13 at 2.24.59 PM.png…]()

**Comment by Avinava** [comment]
@jawills can you see the response of the api as well ?
it is currently using tooling api to fetch all the classes

`SELECT Id, Name, Body, ApiVersion, Status FROM ApexClass WHERE NamespacePrefix = null`

^ this is the query that is used in the backend, can you try running in your org and see ?
The other thing I can think of is , do you have namespace activated in your dev org ? if so then classes won't show up in the list

**Comment by jawills** [comment]
@Avinava this makes sense. The org I am running from is a developer org, so it has a namespace. Is it possible to add this in your query? You can query the namespace from the organization like so

```
SELECT Id, NamespacePrefix FROM Organization
```

and then add this to your apex class query like so:
```
SELECT Id, Name, Body, ApiVersion, Status FROM ApexClass WHERE NamespacePrefix = null OR NamespacePrefix = 'org-prefix'
```

I can try to write a pr but it may take some time

**Comment by Avinava** [comment]
@jawills I will work on a fix, but meanwhile you can try the app in different org

**Comment by Avinava** [comment]
@jawills I have added a fix hopefully that should handle this issue, let me know if that works for you

**Comment by jawills** [comment]
Looks like the fix you made resolved this. Thank you! Will keep poking around
