### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by GastonLopezz** [Avinava/sfdc-neo#62]
I am trying to create a test class for other class and when I press the Test class button after selecting the class I get a 502 Bad Gateway Issue.
<img width="1132" alt="image" src="https://github.com/Avinava/sfdc-neo/assets/39913987/ffdfc1a3-0f3d-4ffc-a76e-c83c7c3c44ac">

<img width="218" alt="image" src="https://github.com/Avinava/sfdc-neo/assets/39913987/1cbad656-3b70-4816-8fb0-a675e05be165">

**Comment by Avinava** [comment]
@GastonLopezz I have deployed a fix, it should be up and running in next 10 mins.
There were too many users that were trying at the same time caused the app to crash

**Comment by GastonLopezz** [comment]
It keeps happening to me, looks like it's a problem related to that apex class since last Friday happened to me too. Maybe because of the `implements Callable` it has?

**Comment by Avinava** [comment]
@GastonLopezz does it keeps happening for a single apex class ?
Also can you let me know how many apex class do you have in this org ?

**Comment by GastonLopezz** [comment]
Yes, for a single apex class. The org has 39 classes.

**Comment by Avinava** [comment]
This should be fixed, Please reopen if it isn't
