### ISSUE TITLE
504 (Gateway Time-out)

### ISSUE THREAD

**Issue by carmineromano995** [Avinava/sfdc-neo#65]
Is there a limit on the classes it can support?
Unfortunately, there are many in my environment and I get this error: 504 (Gateway Time-out)

**Comment by Avinava** [comment]
@carmineromano995 can you may be retry the test class generation ?


Looks like based on your comments if there are too many classes in an org, the automatic test factory detection is failing and crashing. I am working on a release so that test factory detection is optional.

**Comment by carmineromano995** [comment]
It looks like I'm running into an error 504 when trying to load the apex classes.

**Comment by Avinava** [comment]
@carmineromano995 how many apex classes you have in your org ?

**Comment by carmineromano995** [comment]
More than 5000 unfortunately

**Comment by Avinava** [comment]
Ahh that can cause the problem, currently the api doesn't have pagination and fetches all the classes, I believe thats causing it to crash.

I will add the fix in next release

**Comment by Avinava** [comment]
@carmineromano995 I added a small optimization, hopefully that should fix loading apex classes for you

**Comment by carmineromano995** [comment]
Thank you very much, now the class loading works fine. I stressed the tool with really complex and very long classes and unfortunately, it doesn't work as I would like, maybe this is an improvement for the future. 
Congratulations on your tool 👍 .
